[workspace]
members = ["s3"]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
axum = "0.7.9"
bytes = "1.9.0"
foundationdb = { version = "0.9.1", features = ["embedded-fdb-include", "fdb-7_3"] }
